// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyClassLibrary;

#nullable disable

namespace MyClassLibrary.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230118094921_Seeding")]
    partial class Seeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MyClassLibrary.Models.ShapeResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("Input1")
                        .HasColumnType("float");

                    b.Property<double>("Input2")
                        .HasColumnType("float");

                    b.Property<double>("Input3")
                        .HasColumnType("float");

                    b.Property<double>("Perimeter")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ShapeResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 2.0,
                            Date = new DateTime(2023, 1, 18, 10, 49, 21, 22, DateTimeKind.Local).AddTicks(7653),
                            Input1 = 1.0,
                            Input2 = 2.0,
                            Input3 = 0.0,
                            Perimeter = 6.0
                        },
                        new
                        {
                            Id = 2,
                            Area = 2.0,
                            Date = new DateTime(2023, 1, 18, 10, 49, 21, 22, DateTimeKind.Local).AddTicks(7745),
                            Input1 = 1.0,
                            Input2 = 2.0,
                            Input3 = 0.0,
                            Perimeter = 6.0
                        },
                        new
                        {
                            Id = 3,
                            Area = 2.0,
                            Date = new DateTime(2023, 1, 18, 10, 49, 21, 22, DateTimeKind.Local).AddTicks(7751),
                            Input1 = 1.0,
                            Input2 = 2.0,
                            Input3 = 0.0,
                            Perimeter = 6.0
                        },
                        new
                        {
                            Id = 4,
                            Area = 2.0,
                            Date = new DateTime(2023, 1, 18, 10, 49, 21, 22, DateTimeKind.Local).AddTicks(7757),
                            Input1 = 1.0,
                            Input2 = 2.0,
                            Input3 = 0.0,
                            Perimeter = 6.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
